- name: Drain node
  community.docker.docker_node:
    hostname: "{{ node_name }}"
    availability: drain

- name: Wait stop
  community.docker.docker_host_info:
    containers: true
  register: task_result
  retries: 30
  delay: 2
  until: task_result.host_info.ContainersRunning == 0
  delegate_to: "{{ node_name }}"

- name: Remove node from cluster
  ansible.builtin.command: "docker node rm {{ node_name }} --force"
  register: output
  changed_when: output == 0
