- name: Deploy and build server
  hosts: deploy
  roles:
    - role: pre_config
      tags: pre_config
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    - role: swarm_init
      tags: swarm_init

- name: Managers
  hosts: managers
  roles:
    - role: pre_config
      tags: pre_config
    - role: swarm_join
      type: manager
      tags: swarm_join
  post_tasks:
    - name: Clear tokens folder
      ansible.builtin.file:
        path: ./tokens
        state: absent
      delegate_to: localhost
      ignore_errors: true
      tags: swarm_join
