- name: Deploy and build server
  hosts: deploy
  roles:
    - role: pre_config
      tags: pre_config
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    # - swarm_init

- name: Managers
  hosts: managers
  roles:
    - role: pre_config
      tags: pre_config
    # - swarm_join
