- name: Preconfig
  hosts: demo
  tasks:
    - name: Setting up docker
      block:
        - name: Add universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
        
        - name: Setting up additional packages
          apt:
            name: 
              - ca-certificates
              - curl
              - gnupg
            update-cache: yes
            cache_valid_time: 86400

        - name: Add Docker official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Setting up repository
          apt_repository:
            repo: >
              deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker

        - name: Setting up docker packages
          apt:
            name: 
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
            update-cache: yes

        - name: Check that the docker is installed and reloaded
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: Setting up docker-compose
      become: yes
      apt:
        name:
          - docker-compose-plugin
        state: present
        update-cache: yes
    
    - name: Completing the installation
      block:
        - name: Add user into docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        - name: Reboot
          reboot:
      become: yes