- name: Setting up docker
  become: true
  block:
    - name: Add universe
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Setting up additional packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - apt-transport-https
          - lsb-release
          - python3-pip
        update-cache: true
        cache_valid_time: 86400

    - name: Add Docker official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Setting up repository
      ansible.builtin.apt_repository:
        repo: >
          deb https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Setting up docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
        update-cache: true

    - name: Check that the docker is installed and reloaded
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

- name: Setting up docker-compose
  become: true
  ansible.builtin.apt:
    name:
      - docker-compose-plugin
    state: present
    update-cache: true

- name: Configuration python additional packages
  block:
    - name: Setting up pip packages
      ansible.builtin.pip:
        name: docker

- name: Completing the installation
  become: true
  block:
    - name: Add user into docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Reboot
      ansible.builtin.reboot:
