galaxy_info:
  role_name: deploy
  author: Egor Pavlovskiy
  description: Deploy microservices into cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: swarm_init
