- name: "[{{ name }}] Config configuration"
  block:
  - name: "[{{ name }}] Create config"
    ansible.builtin.include_tasks:
        file: "./config-create.yml"
  tags:
    - "{{ name }}"

  rescue:
    - name: "[{{ name }}] Removing config"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Create config"
      ansible.builtin.include_tasks:
        file: "./config-create.yml"
