- name: "[{{ name }}] Post the service"
  block:
  - name: "[{{ name }}] Posting the service"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "rabbitmq:{{ version }}"
      state: present
      networks:
        - "{{ network_name }}"
      env:
        - RABBITMQ_DEFAULT_USER={{ rmq.user }}
        - RABBITMQ_DEFAULT_PASS=admin={{ rmq.password }}
  tags:
    - "{{ name }}"
