galaxy_info:
  role_name: swarm_join
  author: Egor Pavlovskiy
  description: Join swarm cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
