- name: Init swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Folder exists
  ansible.builtin.file:
    path: ./tokens
    state: directory
    mode: '0644'
  delegate_to: localhost

- name: Save manager token
  ansible.builtin.copy:
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinToken.Manager }}"
    mode: '0644'
  delegate_to: localhost

- name: Save worker token
  ansible.builtin.copy:
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinToken.Worker }}"
    mode: '0644'
  delegate_to: localhost
