- name: Deploy and build server
  hosts: deploy
  roles:
    - role: pre_config
      tags: pre_config
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    - role: swarm_init
      tags: swarm_init
    - role: swarm_leave
      node_name: server2
      tags: swarm_leave

- name: Managers
  hosts: managers
  roles:
    - role: pre_config
      tags: pre_config
    - role: swarm_join
      type: manager
      tags: swarm_join
