- name: "[{{ name }}] Secret configuration"
  block:
  - name: "[{{ name }}] Create secret"
    ansible.builtin.include_tasks:
        file: "./secret-create.yml"
  tags:
    - "{{ name }}"

  rescue:
    - name: "[{{ name }}] Removing service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Create secret"
      ansible.builtin.include_tasks:
        file: "./secret-create.yml"
