galaxy_info:
  role_name: swarm_init
  author: Egor Pavlovskiy
  description: Init swarm cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: deploy
