- name: "[{{ name }}] Post the service"
  block:
  - name: "[{{ name }}] Posting the service"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "{{ registry_name }}/{{ name }}:{{ version }}"
      state: present
      force_update: true
      networks:
        - "{{ network_name }}"
      publish:
        - mode: ingress
          protocol: tcp
          target_port: 80
          published_port: 3001
  tags:
    - "{{ name }}"
